clear all;
close all;
clc;
omega_zero = pi/4;
r = 0.99;
z = exp(1i*pi);
b0 = power(abs(1 - 2*cos(omega_zero) * power(z,-1) + power(z,-2))/abs(1 - 2*r*cos(omega_zero) * power(z,-1) + power(z,-2)*power(r,2)),-1);
% frequency_response(b0 * [1, -2*r*cos(omega_zero), power(r,2)],1);
freqz(b0 * [1, -2*cos(omega_zero), 1],[1, -2*r*cos(omega_zero), power(r,2)]);
saveas(gcf,'results_0.99.jpg');
fvtool(b0 * [1, -2*cos(omega_zero), 1],[1, -2*r*cos(omega_zero), power(r,2)]);